# docker compose 
version: '3.8'
services:
  backend:
    build: .
    container_name: stayease-user-management-backend
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb+srv://tharinduherath2426_db_user:Test1234@cluster0.1mxmtlb.mongodb.net/stayease_auth?retryWrites=true&w=majority
    restart: unless-stopped
